# Generated by Django 5.2.5 on 2025-09-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('e_mail', models.CharField(max_length=100)),
                ('first_pet_name', models.CharField(max_length=11)),
                ('your_bestfriend', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Additonal_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Civil_Status', models.CharField(max_length=100)),
                ('Nationality', models.CharField(max_length=100)),
                ('Religion', models.CharField(max_length=100)),
                ('Person_with_Disability', models.BooleanField()),
                ('Sped_Student', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=100)),
                ('Province', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Barangay', models.CharField(max_length=11)),
                ('Street', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EducationBG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('Achievements', models.CharField(max_length=100)),
                ('AVG_grade', models.IntegerField()),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Contact_No', models.IntegerField()),
                ('Student_ID', models.CharField(max_length=100)),
            ],
        ),
    ]
