# Generated by Django 5.2.5 on 2025-09-05 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_account_additonal_info_address_educationbg_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestingDatabase',
        ),
    ]
