# Generated by Django 5.2.5 on 2025-09-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0003_delete_testingdatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationbg',
            name='AVG_grade',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='educationbg',
            name='Year',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='students',
            name='Contact_No',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
    ]
