# Generated by Django 5.2.5 on 2025-09-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0004_alter_educationbg_avg_grade_alter_educationbg_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_pet_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='Barangay',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='educationbg',
            name='Year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='students',
            name='Contact_No',
            field=models.CharField(max_length=12),
        ),
    ]
